# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f9ac7675804b9e33c23d046e059b08171083d3642d6823c2fb749be55cad01f44ca3d6cd2942dd1fc64c90faea5a5ee9515a4327f6e8fb9bfcf4cfea899e275

test:
  secret_key_base: 548ea9ffd6ffdf9dd4733bff81738cd8371874da3607534a1fe77a2d0f1d5580364431050078842a1b0bf2e8a31d2f16d22955408e84bf0d1a10137f757f7288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
